package org.yournamehere.client;
// Generated 25.10.2012 22:48:57 by Hibernate Tools 3.2.1.GA


import com.smartgwt.client.widgets.grid.ListGridRecord;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,schema="mbsystem"
)
public class Test /*extends ListGridRecord*/ implements java.io.Serializable {


     private int id;
     private String nazev;
     private String text;
     private byte[] priloha;

    public Test() {
    }

	
    public Test(int id) {
        this.id = id;
    }
    public Test(int id, String nazev, String text, byte[] priloha) {
       this.id = id;
       this.nazev = nazev;
       this.text = text;
       this.priloha = priloha;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="nazev", length=30)
    public String getNazev() {
        return this.nazev;
    }
    
    public void setNazev(String nazev) {
        this.nazev = nazev;
    }
    
    @Column(name="text")
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    @Column(name="priloha")
    public byte[] getPriloha() {
        return this.priloha;
    }
    
    public void setPriloha(byte[] priloha) {
        this.priloha = priloha;
    }




}


